CREATE TABLE member (ID BIGINT NOT NULL, FIRST_NAME VARCHAR(255) NOT NULL, LAST_NAME VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE status (ID BIGINT NOT NULL, MEMBER_ID BIGINT, NAME VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
ALTER TABLE status ADD CONSTRAINT FK_status_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES member (ID);
CREATE SEQUENCE status_seq INCREMENT BY 50 START WITH 50;
CREATE SEQUENCE member_seq INCREMENT BY 50 START WITH 50;
